[package]
name = "reaper-kbd"
description = "Parser and types for REAPER keyboard mapping (.kbd) files"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
bitflags = { workspace = true }

[lints]
workspace = true
