//! Media Item default behaviors (left drag, click, double click)

use crate::input::mouse_modifiers::behaviors::shared::traits::{BehaviorDisplay, BehaviorId};

/// Media Item left drag behaviors
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaItemLeftDragBehavior {
    NoAction,
    MoveItem,
    CopyItem,
    MoveItemContents,
    MoveItemIgnoringSnap,
    CopyItemIgnoringSnap,
    MoveItemEdgesButNotContent,
    RenderItemToNewFile,
    OpenSourceFileInEditorOrExternalApplication,
    MoveItemIgnoringSelectionGrouping,
    MoveItemIgnoringSnapAndSelectionGrouping,
    AdjustTakePitchSemitones,
    AdjustTakePitchFine,
    MoveItemIgnoringTimeSelection,
    MoveItemIgnoringSnapAndTimeSelection,
    MoveItemIgnoringTimeSelectionAndSelectionGrouping,
    MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping,
    CopyItemIgnoringTimeSelection,
    CopyItemIgnoringSnapAndTimeSelection,
    SelectTime,
    AdjustItemVolume,
    AdjustItemVolumeFine,
    MoveItemAndTimeSelection,
    MoveItemAndTimeSelectionIgnoringSnap,
    CopyItemAndMoveTimeSelection,
    CopyItemAndMoveTimeSelectionIgnoringSnap,
    SelectTimeIgnoringSnap,
    MarqueeSelectItems,
    MarqueeSelectItemsAndTime,
    MarqueeSelectItemsAndTimeIgnoringSnap,
    MarqueeToggleItemSelection,
    MarqueeAddToItemSelection,
    MoveItemVertically,
    MoveItemVerticallyIgnoringSelectionGrouping,
    MoveItemVerticallyIgnoringTimeSelection,
    MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping,
    CopyItemVertically,
    CopyItemVerticallyIgnoringTimeSelection,
    MoveItemContentsIgnoringSelectionGrouping,
    CopyItemPoolingMidiSourceData,
    CopyItemIgnoringSnapPoolingMidiSourceData,
    CopyItemIgnoringTimeSelectionPoolingMidiSourceData,
    CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData,
    CopyItemVerticallyPoolingMidiSourceData,
    CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData,
    CopyItemAndMoveTimeSelectionPoolingMidiSourceData,
    CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData,
    AdjustTakePan,
    MarqueeZoom,
    MoveItemIgnoringTimeSelectionDisablingRippleEdit,
    MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack,
    MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks,
    MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit,
    MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack,
    MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks,
    MoveItemContentsRippleAllAdjacentItems,
    MoveItemContentsRippleEarlierAdjacentItems,
    MoveItemContentsAndRightEdgeRippleLaterAdjacentItems,
    SelectRazorEditArea,
    SelectRazorEditAreaIgnoringSnap,
    AddToRazorEditArea,
    AddToRazorEditAreaIgnoringSnap,
    SelectRazorEditAreaAndTime,
    SelectRazorEditAreaAndTimeIgnoringSnap,
    Unknown(u32),
}

impl BehaviorId for MediaItemLeftDragBehavior {
    fn from_behavior_id(behavior_id: u32) -> Self {
        match behavior_id {
            0 => MediaItemLeftDragBehavior::NoAction,
            1 => MediaItemLeftDragBehavior::MoveItem,
            2 => MediaItemLeftDragBehavior::CopyItem,
            3 => MediaItemLeftDragBehavior::MoveItemContents,
            4 => MediaItemLeftDragBehavior::MoveItemIgnoringSnap,
            5 => MediaItemLeftDragBehavior::CopyItemIgnoringSnap,
            6 => MediaItemLeftDragBehavior::MoveItemEdgesButNotContent,
            7 => MediaItemLeftDragBehavior::RenderItemToNewFile,
            8 => MediaItemLeftDragBehavior::OpenSourceFileInEditorOrExternalApplication,
            9 => MediaItemLeftDragBehavior::MoveItemIgnoringSelectionGrouping,
            10 => MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndSelectionGrouping,
            11 => MediaItemLeftDragBehavior::AdjustTakePitchSemitones,
            12 => MediaItemLeftDragBehavior::AdjustTakePitchFine,
            13 => MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelection,
            14 => MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelection,
            15 => MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionAndSelectionGrouping,
            16 => MediaItemLeftDragBehavior::MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping,
            17 => MediaItemLeftDragBehavior::CopyItemIgnoringTimeSelection,
            18 => MediaItemLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelection,
            19 => MediaItemLeftDragBehavior::SelectTime,
            20 => MediaItemLeftDragBehavior::AdjustItemVolume,
            21 => MediaItemLeftDragBehavior::AdjustItemVolumeFine,
            22 => MediaItemLeftDragBehavior::MoveItemAndTimeSelection,
            23 => MediaItemLeftDragBehavior::MoveItemAndTimeSelectionIgnoringSnap,
            24 => MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelection,
            25 => MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnap,
            26 => MediaItemLeftDragBehavior::SelectTimeIgnoringSnap,
            27 => MediaItemLeftDragBehavior::MarqueeSelectItems,
            28 => MediaItemLeftDragBehavior::MarqueeSelectItemsAndTime,
            29 => MediaItemLeftDragBehavior::MarqueeSelectItemsAndTimeIgnoringSnap,
            30 => MediaItemLeftDragBehavior::MarqueeToggleItemSelection,
            31 => MediaItemLeftDragBehavior::MarqueeAddToItemSelection,
            32 => MediaItemLeftDragBehavior::MoveItemVertically,
            33 => MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringSelectionGrouping,
            34 => MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelection,
            35 => MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping,
            36 => MediaItemLeftDragBehavior::CopyItemVertically,
            37 => MediaItemLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelection,
            38 => MediaItemLeftDragBehavior::MoveItemContentsIgnoringSelectionGrouping,
            39 => MediaItemLeftDragBehavior::CopyItemPoolingMidiSourceData,
            40 => MediaItemLeftDragBehavior::CopyItemIgnoringSnapPoolingMidiSourceData,
            41 => MediaItemLeftDragBehavior::CopyItemIgnoringTimeSelectionPoolingMidiSourceData,
            42 => MediaItemLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData,
            43 => MediaItemLeftDragBehavior::CopyItemVerticallyPoolingMidiSourceData,
            44 => MediaItemLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData,
            45 => MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionPoolingMidiSourceData,
            46 => MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData,
            47 => MediaItemLeftDragBehavior::AdjustTakePan,
            48 => MediaItemLeftDragBehavior::MarqueeZoom,
            49 => MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionDisablingRippleEdit,
            50 => MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack,
            51 => MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks,
            52 => MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit,
            53 => MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack,
            54 => MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks,
            55 => MediaItemLeftDragBehavior::MoveItemContentsRippleAllAdjacentItems,
            56 => MediaItemLeftDragBehavior::MoveItemContentsRippleEarlierAdjacentItems,
            57 => MediaItemLeftDragBehavior::MoveItemContentsAndRightEdgeRippleLaterAdjacentItems,
            62 => MediaItemLeftDragBehavior::SelectRazorEditArea,
            63 => MediaItemLeftDragBehavior::SelectRazorEditAreaIgnoringSnap,
            64 => MediaItemLeftDragBehavior::AddToRazorEditArea,
            65 => MediaItemLeftDragBehavior::AddToRazorEditAreaIgnoringSnap,
            66 => MediaItemLeftDragBehavior::SelectRazorEditAreaAndTime,
            67 => MediaItemLeftDragBehavior::SelectRazorEditAreaAndTimeIgnoringSnap,
            id => MediaItemLeftDragBehavior::Unknown(id),
        }
    }

    fn to_behavior_id(&self) -> u32 {
        match self {
            MediaItemLeftDragBehavior::NoAction => 0,
            MediaItemLeftDragBehavior::MoveItem => 1,
            MediaItemLeftDragBehavior::CopyItem => 2,
            MediaItemLeftDragBehavior::MoveItemContents => 3,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnap => 4,
            MediaItemLeftDragBehavior::CopyItemIgnoringSnap => 5,
            MediaItemLeftDragBehavior::MoveItemEdgesButNotContent => 6,
            MediaItemLeftDragBehavior::RenderItemToNewFile => 7,
            MediaItemLeftDragBehavior::OpenSourceFileInEditorOrExternalApplication => 8,
            MediaItemLeftDragBehavior::MoveItemIgnoringSelectionGrouping => 9,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndSelectionGrouping => 10,
            MediaItemLeftDragBehavior::AdjustTakePitchSemitones => 11,
            MediaItemLeftDragBehavior::AdjustTakePitchFine => 12,
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelection => 13,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelection => 14,
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionAndSelectionGrouping => 15,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping => 16,
            MediaItemLeftDragBehavior::CopyItemIgnoringTimeSelection => 17,
            MediaItemLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelection => 18,
            MediaItemLeftDragBehavior::SelectTime => 19,
            MediaItemLeftDragBehavior::AdjustItemVolume => 20,
            MediaItemLeftDragBehavior::AdjustItemVolumeFine => 21,
            MediaItemLeftDragBehavior::MoveItemAndTimeSelection => 22,
            MediaItemLeftDragBehavior::MoveItemAndTimeSelectionIgnoringSnap => 23,
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelection => 24,
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnap => 25,
            MediaItemLeftDragBehavior::SelectTimeIgnoringSnap => 26,
            MediaItemLeftDragBehavior::MarqueeSelectItems => 27,
            MediaItemLeftDragBehavior::MarqueeSelectItemsAndTime => 28,
            MediaItemLeftDragBehavior::MarqueeSelectItemsAndTimeIgnoringSnap => 29,
            MediaItemLeftDragBehavior::MarqueeToggleItemSelection => 30,
            MediaItemLeftDragBehavior::MarqueeAddToItemSelection => 31,
            MediaItemLeftDragBehavior::MoveItemVertically => 32,
            MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringSelectionGrouping => 33,
            MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelection => 34,
            MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping => 35,
            MediaItemLeftDragBehavior::CopyItemVertically => 36,
            MediaItemLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelection => 37,
            MediaItemLeftDragBehavior::MoveItemContentsIgnoringSelectionGrouping => 38,
            MediaItemLeftDragBehavior::CopyItemPoolingMidiSourceData => 39,
            MediaItemLeftDragBehavior::CopyItemIgnoringSnapPoolingMidiSourceData => 40,
            MediaItemLeftDragBehavior::CopyItemIgnoringTimeSelectionPoolingMidiSourceData => 41,
            MediaItemLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData => 42,
            MediaItemLeftDragBehavior::CopyItemVerticallyPoolingMidiSourceData => 43,
            MediaItemLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData => 44,
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionPoolingMidiSourceData => 45,
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData => 46,
            MediaItemLeftDragBehavior::AdjustTakePan => 47,
            MediaItemLeftDragBehavior::MarqueeZoom => 48,
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionDisablingRippleEdit => 49,
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack => 50,
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks => 51,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit => 52,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack => 53,
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks => 54,
            MediaItemLeftDragBehavior::MoveItemContentsRippleAllAdjacentItems => 55,
            MediaItemLeftDragBehavior::MoveItemContentsRippleEarlierAdjacentItems => 56,
            MediaItemLeftDragBehavior::MoveItemContentsAndRightEdgeRippleLaterAdjacentItems => 57,
            MediaItemLeftDragBehavior::SelectRazorEditArea => 62,
            MediaItemLeftDragBehavior::SelectRazorEditAreaIgnoringSnap => 63,
            MediaItemLeftDragBehavior::AddToRazorEditArea => 64,
            MediaItemLeftDragBehavior::AddToRazorEditAreaIgnoringSnap => 65,
            MediaItemLeftDragBehavior::SelectRazorEditAreaAndTime => 66,
            MediaItemLeftDragBehavior::SelectRazorEditAreaAndTimeIgnoringSnap => 67,
            MediaItemLeftDragBehavior::Unknown(id) => *id,
        }
    }
}

impl BehaviorDisplay for MediaItemLeftDragBehavior {
    fn display_name(&self) -> &'static str {
        match self {
            MediaItemLeftDragBehavior::NoAction => "No action",
            MediaItemLeftDragBehavior::MoveItem => "Move item",
            MediaItemLeftDragBehavior::CopyItem => "Copy item",
            MediaItemLeftDragBehavior::MoveItemContents => "Move item contents",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnap => "Move item ignoring snap",
            MediaItemLeftDragBehavior::CopyItemIgnoringSnap => "Copy item ignoring snap",
            MediaItemLeftDragBehavior::MoveItemEdgesButNotContent => "Move item edges but not content",
            MediaItemLeftDragBehavior::RenderItemToNewFile => "Render item to new file",
            MediaItemLeftDragBehavior::OpenSourceFileInEditorOrExternalApplication => "Open source file in editor or external application",
            MediaItemLeftDragBehavior::MoveItemIgnoringSelectionGrouping => "Move item ignoring selection/grouping",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndSelectionGrouping => "Move item ignoring snap and selection/grouping",
            MediaItemLeftDragBehavior::AdjustTakePitchSemitones => "Adjust take pitch (semitones)",
            MediaItemLeftDragBehavior::AdjustTakePitchFine => "Adjust take pitch (fine)",
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelection => "Move item ignoring time selection",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelection => "Move item ignoring snap and time selection",
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionAndSelectionGrouping => "Move item ignoring time selection and selection/grouping",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping => "Move item ignoring snap, time selection, and selection/grouping",
            MediaItemLeftDragBehavior::CopyItemIgnoringTimeSelection => "Copy item ignoring time selection",
            MediaItemLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelection => "Copy item ignoring snap and time selection",
            MediaItemLeftDragBehavior::SelectTime => "Select time",
            MediaItemLeftDragBehavior::AdjustItemVolume => "Adjust item volume",
            MediaItemLeftDragBehavior::AdjustItemVolumeFine => "Adjust item volume (fine)",
            MediaItemLeftDragBehavior::MoveItemAndTimeSelection => "Move item and time selection",
            MediaItemLeftDragBehavior::MoveItemAndTimeSelectionIgnoringSnap => "Move item and time selection ignoring snap",
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelection => "Copy item and move time selection",
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnap => "Copy item and move time selection ignoring snap",
            MediaItemLeftDragBehavior::SelectTimeIgnoringSnap => "Select time ignoring snap",
            MediaItemLeftDragBehavior::MarqueeSelectItems => "Marquee select items",
            MediaItemLeftDragBehavior::MarqueeSelectItemsAndTime => "Marquee select items and time",
            MediaItemLeftDragBehavior::MarqueeSelectItemsAndTimeIgnoringSnap => "Marquee select items and time ignoring snap",
            MediaItemLeftDragBehavior::MarqueeToggleItemSelection => "Marquee toggle item selection",
            MediaItemLeftDragBehavior::MarqueeAddToItemSelection => "Marquee add to item selection",
            MediaItemLeftDragBehavior::MoveItemVertically => "Move item vertically",
            MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringSelectionGrouping => "Move item vertically ignoring selection/grouping",
            MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelection => "Move item vertically ignoring time selection",
            MediaItemLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping => "Move item vertically ignoring time selection and selection/grouping",
            MediaItemLeftDragBehavior::CopyItemVertically => "Copy item vertically",
            MediaItemLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelection => "Copy item vertically ignoring time selection",
            MediaItemLeftDragBehavior::MoveItemContentsIgnoringSelectionGrouping => "Move item contents ignoring selection/grouping",
            MediaItemLeftDragBehavior::CopyItemPoolingMidiSourceData => "Copy item, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemIgnoringSnapPoolingMidiSourceData => "Copy item ignoring snap, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemIgnoringTimeSelectionPoolingMidiSourceData => "Copy item ignoring time selection, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData => "Copy item ignoring snap and time selection, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemVerticallyPoolingMidiSourceData => "Copy item vertically, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData => "Copy item vertically ignoring time selection, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionPoolingMidiSourceData => "Copy item and move time selection, pooling MIDI source data",
            MediaItemLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData => "Copy item and move time selection ignoring snap, pooling MIDI source data",
            MediaItemLeftDragBehavior::AdjustTakePan => "Adjust take pan",
            MediaItemLeftDragBehavior::MarqueeZoom => "Marquee zoom",
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionDisablingRippleEdit => "Move item ignoring time selection, disabling ripple edit",
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack => "Move item ignoring time selection, enabling ripple edit for this track",
            MediaItemLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks => "Move item ignoring time selection, enabling ripple edit for all tracks",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit => "Move item ignoring snap and time selection, disabling ripple edit",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack => "Move item ignoring snap and time selection, enabling ripple edit for this track",
            MediaItemLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks => "Move item ignoring snap and time selection, enabling ripple edit for all tracks",
            MediaItemLeftDragBehavior::MoveItemContentsRippleAllAdjacentItems => "Move item contents, ripple all adjacent items",
            MediaItemLeftDragBehavior::MoveItemContentsRippleEarlierAdjacentItems => "Move item contents, ripple earlier adjacent items",
            MediaItemLeftDragBehavior::MoveItemContentsAndRightEdgeRippleLaterAdjacentItems => "Move item contents and right edge, ripple later adjacent items",
            MediaItemLeftDragBehavior::SelectRazorEditArea => "Select razor edit area",
            MediaItemLeftDragBehavior::SelectRazorEditAreaIgnoringSnap => "Select razor edit area ignoring snap",
            MediaItemLeftDragBehavior::AddToRazorEditArea => "Add to razor edit area",
            MediaItemLeftDragBehavior::AddToRazorEditAreaIgnoringSnap => "Add to razor edit area ignoring snap",
            MediaItemLeftDragBehavior::SelectRazorEditAreaAndTime => "Select razor edit area and time",
            MediaItemLeftDragBehavior::SelectRazorEditAreaAndTimeIgnoringSnap => "Select razor edit area and time ignoring snap",
            MediaItemLeftDragBehavior::Unknown(_) => "Unknown behavior",
        }
    }
}

/// Media Item click behaviors
///
/// Note: Behavior IDs are based on Ultraschall documentation.
/// IDs 0-15 and 20 are confirmed. Other IDs need verification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaItemClickBehavior {
    NoAction,
    SelectItemAndMoveEditCursor,
    SelectItemAndMoveEditCursorIgnoringSnap,
    SelectItem,
    ToggleItemSelection,
    AddARangeOfItemsToSelection,
    AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection,
    AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap,
    ExtendTimeSelection,
    ExtendTimeSelectionIgnoringSnap,
    AddARangeOfItemsToSelectionAndExtendTimeSelection,
    AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap,
    SelectItemIgnoringGrouping,
    RestorePreviousZoomScroll,
    RestorePreviousZoomLevel,
    AddStretchMarker,
    // ID 20 confirmed from Ultraschall docs
    ExtendRazorEditArea,
    Unknown(u32),
}

impl BehaviorId for MediaItemClickBehavior {
    fn from_behavior_id(behavior_id: u32) -> Self {
        match behavior_id {
            0 => MediaItemClickBehavior::NoAction,
            1 => MediaItemClickBehavior::SelectItemAndMoveEditCursor,
            2 => MediaItemClickBehavior::SelectItemAndMoveEditCursorIgnoringSnap,
            3 => MediaItemClickBehavior::SelectItem,
            4 => MediaItemClickBehavior::ToggleItemSelection,
            5 => MediaItemClickBehavior::AddARangeOfItemsToSelection,
            6 => MediaItemClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection,
            7 => MediaItemClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap,
            8 => MediaItemClickBehavior::ExtendTimeSelection,
            9 => MediaItemClickBehavior::ExtendTimeSelectionIgnoringSnap,
            10 => MediaItemClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelection,
            11 => MediaItemClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap,
            12 => MediaItemClickBehavior::SelectItemIgnoringGrouping,
            13 => MediaItemClickBehavior::RestorePreviousZoomScroll,
            14 => MediaItemClickBehavior::RestorePreviousZoomLevel,
            15 => MediaItemClickBehavior::AddStretchMarker,
            20 => MediaItemClickBehavior::ExtendRazorEditArea,
            id => MediaItemClickBehavior::Unknown(id),
        }
    }

    fn to_behavior_id(&self) -> u32 {
        match self {
            MediaItemClickBehavior::NoAction => 0,
            MediaItemClickBehavior::SelectItemAndMoveEditCursor => 1,
            MediaItemClickBehavior::SelectItemAndMoveEditCursorIgnoringSnap => 2,
            MediaItemClickBehavior::SelectItem => 3,
            MediaItemClickBehavior::ToggleItemSelection => 4,
            MediaItemClickBehavior::AddARangeOfItemsToSelection => 5,
            MediaItemClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection => 6,
            MediaItemClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap => 7,
            MediaItemClickBehavior::ExtendTimeSelection => 8,
            MediaItemClickBehavior::ExtendTimeSelectionIgnoringSnap => 9,
            MediaItemClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelection => 10,
            MediaItemClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap => 11,
            MediaItemClickBehavior::SelectItemIgnoringGrouping => 12,
            MediaItemClickBehavior::RestorePreviousZoomScroll => 13,
            MediaItemClickBehavior::RestorePreviousZoomLevel => 14,
            MediaItemClickBehavior::AddStretchMarker => 15,
            MediaItemClickBehavior::ExtendRazorEditArea => 20,
            MediaItemClickBehavior::Unknown(id) => *id,
        }
    }
}

impl BehaviorDisplay for MediaItemClickBehavior {
    fn display_name(&self) -> &'static str {
        match self {
            MediaItemClickBehavior::NoAction => "No action",
            MediaItemClickBehavior::SelectItemAndMoveEditCursor => "Select item and move edit cursor",
            MediaItemClickBehavior::SelectItemAndMoveEditCursorIgnoringSnap => "Select item and move edit cursor ignoring snap",
            MediaItemClickBehavior::SelectItem => "Select item",
            MediaItemClickBehavior::ToggleItemSelection => "Toggle item selection",
            MediaItemClickBehavior::AddARangeOfItemsToSelection => "Add a range of items to selection",
            MediaItemClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection => "Add a range of items to selection, if already selected extend time selection",
            MediaItemClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap => "Add a range of items to selection, if already selected extend time selection ignoring snap",
            MediaItemClickBehavior::ExtendTimeSelection => "Extend time selection",
            MediaItemClickBehavior::ExtendTimeSelectionIgnoringSnap => "Extend time selection ignoring snap",
            MediaItemClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelection => "Add a range of items to selection and extend time selection",
            MediaItemClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap => "Add a range of items to selection and extend time selection ignoring snap",
            MediaItemClickBehavior::SelectItemIgnoringGrouping => "Select item ignoring grouping",
            MediaItemClickBehavior::RestorePreviousZoomScroll => "Restore previous zoom/scroll",
            MediaItemClickBehavior::RestorePreviousZoomLevel => "Restore previous zoom level",
            MediaItemClickBehavior::AddStretchMarker => "Add stretch marker",
            MediaItemClickBehavior::ExtendRazorEditArea => "Extend razor edit area",
            MediaItemClickBehavior::Unknown(_) => "Unknown behavior",
        }
    }
}

/// Media Item double click behaviors
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaItemDoubleClickBehavior {
    NoAction,
    OpenMediaItemInExternalEditor,
    SetTimeSelectionToItem,
    SetLoopPointsToItem,
    ShowMediaItemProperties,
    ShowMediaItemSourceProperties,
    MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties,
    ShowTakeList,
    ShowTakePropsList,
    Unknown(u32),
}

impl BehaviorId for MediaItemDoubleClickBehavior {
    fn from_behavior_id(behavior_id: u32) -> Self {
        match behavior_id {
            0 => MediaItemDoubleClickBehavior::NoAction,
            1 => MediaItemDoubleClickBehavior::OpenMediaItemInExternalEditor,
            2 => MediaItemDoubleClickBehavior::SetTimeSelectionToItem,
            3 => MediaItemDoubleClickBehavior::SetLoopPointsToItem,
            4 => MediaItemDoubleClickBehavior::ShowMediaItemProperties,
            5 => MediaItemDoubleClickBehavior::ShowMediaItemSourceProperties,
            6 => MediaItemDoubleClickBehavior::MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties,
            7 => MediaItemDoubleClickBehavior::ShowTakeList,
            8 => MediaItemDoubleClickBehavior::ShowTakePropsList,
            id => MediaItemDoubleClickBehavior::Unknown(id),
        }
    }

    fn to_behavior_id(&self) -> u32 {
        match self {
            MediaItemDoubleClickBehavior::NoAction => 0,
            MediaItemDoubleClickBehavior::OpenMediaItemInExternalEditor => 1,
            MediaItemDoubleClickBehavior::SetTimeSelectionToItem => 2,
            MediaItemDoubleClickBehavior::SetLoopPointsToItem => 3,
            MediaItemDoubleClickBehavior::ShowMediaItemProperties => 4,
            MediaItemDoubleClickBehavior::ShowMediaItemSourceProperties => 5,
            MediaItemDoubleClickBehavior::MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties => 6,
            MediaItemDoubleClickBehavior::ShowTakeList => 7,
            MediaItemDoubleClickBehavior::ShowTakePropsList => 8,
            MediaItemDoubleClickBehavior::Unknown(id) => *id,
        }
    }
}

impl BehaviorDisplay for MediaItemDoubleClickBehavior {
    fn display_name(&self) -> &'static str {
        match self {
            MediaItemDoubleClickBehavior::NoAction => "No action",
            MediaItemDoubleClickBehavior::OpenMediaItemInExternalEditor => "Open media item in external editor",
            MediaItemDoubleClickBehavior::SetTimeSelectionToItem => "Set time selection to item",
            MediaItemDoubleClickBehavior::SetLoopPointsToItem => "Set loop points to item",
            MediaItemDoubleClickBehavior::ShowMediaItemProperties => "Show media item properties",
            MediaItemDoubleClickBehavior::ShowMediaItemSourceProperties => "Show media item source properties",
            MediaItemDoubleClickBehavior::MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties => "MIDI: open in editor, Subprojects: open project, Audio: show media item properties",
            MediaItemDoubleClickBehavior::ShowTakeList => "Show take list",
            MediaItemDoubleClickBehavior::ShowTakePropsList => "Show take props list",
            MediaItemDoubleClickBehavior::Unknown(_) => "Unknown behavior",
        }
    }
}
