//! Media Item lower behaviors

use crate::input::mouse_modifiers::behaviors::shared::traits::{BehaviorDisplay, BehaviorId};

/// Media Item lower left drag behaviors
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaItemLowerLeftDragBehavior {
    PassThroughToItemDragContext,
    MoveItem,
    CopyItem,
    MoveItemContents,
    MoveItemIgnoringSnap,
    CopyItemIgnoringSnap,
    MoveItemEdgesButNotContent,
    RenderItemToNewFile,
    OpenSourceFileInEditorOrExternalApplication,
    MoveItemIgnoringSelectionGrouping,
    MoveItemIgnoringSnapAndSelectionGrouping,
    AdjustTakePitchSemitones,
    AdjustTakePitchFine,
    MoveItemIgnoringTimeSelection,
    MoveItemIgnoringSnapAndTimeSelection,
    MoveItemIgnoringTimeSelectionAndSelectionGrouping,
    MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping,
    CopyItemIgnoringTimeSelection,
    CopyItemIgnoringSnapAndTimeSelection,
    SelectTime,
    AdjustItemVolume,
    AdjustItemVolumeFine,
    MoveItemAndTimeSelection,
    MoveItemAndTimeSelectionIgnoringSnap,
    CopyItemAndMoveTimeSelection,
    CopyItemAndMoveTimeSelectionIgnoringSnap,
    SelectTimeIgnoringSnap,
    MarqueeSelectItems,
    MarqueeSelectItemsAndTime,
    MarqueeSelectItemsAndTimeIgnoringSnap,
    MarqueeToggleItemSelection,
    MarqueeAddToItemSelection,
    MoveItemVertically,
    MoveItemVerticallyIgnoringSelectionGrouping,
    MoveItemVerticallyIgnoringTimeSelection,
    MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping,
    CopyItemVertically,
    CopyItemVerticallyIgnoringTimeSelection,
    MoveItemContentsIgnoringSelectionGrouping,
    CopyItemPoolingMidiSourceData,
    CopyItemIgnoringSnapPoolingMidiSourceData,
    CopyItemIgnoringTimeSelectionPoolingMidiSourceData,
    CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData,
    CopyItemVerticallyPoolingMidiSourceData,
    CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData,
    CopyItemAndMoveTimeSelectionPoolingMidiSourceData,
    CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData,
    AdjustTakePan,
    MarqueeZoom,
    MoveItemIgnoringTimeSelectionDisablingRippleEdit,
    MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack,
    MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks,
    MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit,
    MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack,
    MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks,
    MoveItemContentsRippleAllAdjacentItems,
    MoveItemContentsRippleEarlierAdjacentItems,
    MoveItemContentsAndRightEdgeRippleLaterAdjacentItems,
    SelectRazorEditArea,
    SelectRazorEditAreaIgnoringSnap,
    AddToRazorEditArea,
    AddToRazorEditAreaIgnoringSnap,
    SelectRazorEditAreaAndTime,
    SelectRazorEditAreaAndTimeIgnoringSnap,
    Unknown(u32),
}

impl BehaviorId for MediaItemLowerLeftDragBehavior {
    fn from_behavior_id(behavior_id: u32) -> Self {
        match behavior_id {
            0 => MediaItemLowerLeftDragBehavior::PassThroughToItemDragContext,
            1 => MediaItemLowerLeftDragBehavior::MoveItem,
            2 => MediaItemLowerLeftDragBehavior::CopyItem,
            3 => MediaItemLowerLeftDragBehavior::MoveItemContents,
            4 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnap,
            5 => MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnap,
            6 => MediaItemLowerLeftDragBehavior::MoveItemEdgesButNotContent,
            7 => MediaItemLowerLeftDragBehavior::RenderItemToNewFile,
            8 => MediaItemLowerLeftDragBehavior::OpenSourceFileInEditorOrExternalApplication,
            9 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSelectionGrouping,
            10 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndSelectionGrouping,
            11 => MediaItemLowerLeftDragBehavior::AdjustTakePitchSemitones,
            12 => MediaItemLowerLeftDragBehavior::AdjustTakePitchFine,
            13 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelection,
            14 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelection,
            15 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionAndSelectionGrouping,
            16 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping,
            17 => MediaItemLowerLeftDragBehavior::CopyItemIgnoringTimeSelection,
            18 => MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelection,
            19 => MediaItemLowerLeftDragBehavior::SelectTime,
            20 => MediaItemLowerLeftDragBehavior::AdjustItemVolume,
            21 => MediaItemLowerLeftDragBehavior::AdjustItemVolumeFine,
            22 => MediaItemLowerLeftDragBehavior::MoveItemAndTimeSelection,
            23 => MediaItemLowerLeftDragBehavior::MoveItemAndTimeSelectionIgnoringSnap,
            24 => MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelection,
            25 => MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnap,
            26 => MediaItemLowerLeftDragBehavior::SelectTimeIgnoringSnap,
            27 => MediaItemLowerLeftDragBehavior::MarqueeSelectItems,
            28 => MediaItemLowerLeftDragBehavior::MarqueeSelectItemsAndTime,
            29 => MediaItemLowerLeftDragBehavior::MarqueeSelectItemsAndTimeIgnoringSnap,
            30 => MediaItemLowerLeftDragBehavior::MarqueeToggleItemSelection,
            31 => MediaItemLowerLeftDragBehavior::MarqueeAddToItemSelection,
            32 => MediaItemLowerLeftDragBehavior::MoveItemVertically,
            33 => MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringSelectionGrouping,
            34 => MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelection,
            35 => MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping,
            36 => MediaItemLowerLeftDragBehavior::CopyItemVertically,
            37 => MediaItemLowerLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelection,
            38 => MediaItemLowerLeftDragBehavior::MoveItemContentsIgnoringSelectionGrouping,
            39 => MediaItemLowerLeftDragBehavior::CopyItemPoolingMidiSourceData,
            40 => MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapPoolingMidiSourceData,
            41 => MediaItemLowerLeftDragBehavior::CopyItemIgnoringTimeSelectionPoolingMidiSourceData,
            42 => MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData,
            43 => MediaItemLowerLeftDragBehavior::CopyItemVerticallyPoolingMidiSourceData,
            44 => MediaItemLowerLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData,
            45 => MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionPoolingMidiSourceData,
            46 => MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData,
            47 => MediaItemLowerLeftDragBehavior::AdjustTakePan,
            48 => MediaItemLowerLeftDragBehavior::MarqueeZoom,
            49 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionDisablingRippleEdit,
            50 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack,
            51 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks,
            52 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit,
            53 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack,
            54 => MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks,
            55 => MediaItemLowerLeftDragBehavior::MoveItemContentsRippleAllAdjacentItems,
            56 => MediaItemLowerLeftDragBehavior::MoveItemContentsRippleEarlierAdjacentItems,
            57 => MediaItemLowerLeftDragBehavior::MoveItemContentsAndRightEdgeRippleLaterAdjacentItems,
            62 => MediaItemLowerLeftDragBehavior::SelectRazorEditArea,
            63 => MediaItemLowerLeftDragBehavior::SelectRazorEditAreaIgnoringSnap,
            64 => MediaItemLowerLeftDragBehavior::AddToRazorEditArea,
            65 => MediaItemLowerLeftDragBehavior::AddToRazorEditAreaIgnoringSnap,
            66 => MediaItemLowerLeftDragBehavior::SelectRazorEditAreaAndTime,
            67 => MediaItemLowerLeftDragBehavior::SelectRazorEditAreaAndTimeIgnoringSnap,
            id => MediaItemLowerLeftDragBehavior::Unknown(id),
        }
    }

    fn to_behavior_id(&self) -> u32 {
        match self {
            MediaItemLowerLeftDragBehavior::PassThroughToItemDragContext => 0,
            MediaItemLowerLeftDragBehavior::MoveItem => 1,
            MediaItemLowerLeftDragBehavior::CopyItem => 2,
            MediaItemLowerLeftDragBehavior::MoveItemContents => 3,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnap => 4,
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnap => 5,
            MediaItemLowerLeftDragBehavior::MoveItemEdgesButNotContent => 6,
            MediaItemLowerLeftDragBehavior::RenderItemToNewFile => 7,
            MediaItemLowerLeftDragBehavior::OpenSourceFileInEditorOrExternalApplication => 8,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSelectionGrouping => 9,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndSelectionGrouping => 10,
            MediaItemLowerLeftDragBehavior::AdjustTakePitchSemitones => 11,
            MediaItemLowerLeftDragBehavior::AdjustTakePitchFine => 12,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelection => 13,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelection => 14,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionAndSelectionGrouping => 15,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping => 16,
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringTimeSelection => 17,
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelection => 18,
            MediaItemLowerLeftDragBehavior::SelectTime => 19,
            MediaItemLowerLeftDragBehavior::AdjustItemVolume => 20,
            MediaItemLowerLeftDragBehavior::AdjustItemVolumeFine => 21,
            MediaItemLowerLeftDragBehavior::MoveItemAndTimeSelection => 22,
            MediaItemLowerLeftDragBehavior::MoveItemAndTimeSelectionIgnoringSnap => 23,
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelection => 24,
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnap => 25,
            MediaItemLowerLeftDragBehavior::SelectTimeIgnoringSnap => 26,
            MediaItemLowerLeftDragBehavior::MarqueeSelectItems => 27,
            MediaItemLowerLeftDragBehavior::MarqueeSelectItemsAndTime => 28,
            MediaItemLowerLeftDragBehavior::MarqueeSelectItemsAndTimeIgnoringSnap => 29,
            MediaItemLowerLeftDragBehavior::MarqueeToggleItemSelection => 30,
            MediaItemLowerLeftDragBehavior::MarqueeAddToItemSelection => 31,
            MediaItemLowerLeftDragBehavior::MoveItemVertically => 32,
            MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringSelectionGrouping => 33,
            MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelection => 34,
            MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping => 35,
            MediaItemLowerLeftDragBehavior::CopyItemVertically => 36,
            MediaItemLowerLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelection => 37,
            MediaItemLowerLeftDragBehavior::MoveItemContentsIgnoringSelectionGrouping => 38,
            MediaItemLowerLeftDragBehavior::CopyItemPoolingMidiSourceData => 39,
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapPoolingMidiSourceData => 40,
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringTimeSelectionPoolingMidiSourceData => 41,
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData => 42,
            MediaItemLowerLeftDragBehavior::CopyItemVerticallyPoolingMidiSourceData => 43,
            MediaItemLowerLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData => 44,
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionPoolingMidiSourceData => 45,
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData => 46,
            MediaItemLowerLeftDragBehavior::AdjustTakePan => 47,
            MediaItemLowerLeftDragBehavior::MarqueeZoom => 48,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionDisablingRippleEdit => 49,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack => 50,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks => 51,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit => 52,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack => 53,
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks => 54,
            MediaItemLowerLeftDragBehavior::MoveItemContentsRippleAllAdjacentItems => 55,
            MediaItemLowerLeftDragBehavior::MoveItemContentsRippleEarlierAdjacentItems => 56,
            MediaItemLowerLeftDragBehavior::MoveItemContentsAndRightEdgeRippleLaterAdjacentItems => 57,
            MediaItemLowerLeftDragBehavior::SelectRazorEditArea => 62,
            MediaItemLowerLeftDragBehavior::SelectRazorEditAreaIgnoringSnap => 63,
            MediaItemLowerLeftDragBehavior::AddToRazorEditArea => 64,
            MediaItemLowerLeftDragBehavior::AddToRazorEditAreaIgnoringSnap => 65,
            MediaItemLowerLeftDragBehavior::SelectRazorEditAreaAndTime => 66,
            MediaItemLowerLeftDragBehavior::SelectRazorEditAreaAndTimeIgnoringSnap => 67,
            MediaItemLowerLeftDragBehavior::Unknown(id) => *id,
        }
    }
}

impl BehaviorDisplay for MediaItemLowerLeftDragBehavior {
    fn display_name(&self) -> &'static str {
        match self {
            MediaItemLowerLeftDragBehavior::PassThroughToItemDragContext => "Pass through to item drag context",
            MediaItemLowerLeftDragBehavior::MoveItem => "Move item",
            MediaItemLowerLeftDragBehavior::CopyItem => "Copy item",
            MediaItemLowerLeftDragBehavior::MoveItemContents => "Move item contents",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnap => "Move item ignoring snap",
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnap => "Copy item ignoring snap",
            MediaItemLowerLeftDragBehavior::MoveItemEdgesButNotContent => "Move item edges but not content",
            MediaItemLowerLeftDragBehavior::RenderItemToNewFile => "Render item to new file",
            MediaItemLowerLeftDragBehavior::OpenSourceFileInEditorOrExternalApplication => "Open source file in editor or external application",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSelectionGrouping => "Move item ignoring selection/grouping",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndSelectionGrouping => "Move item ignoring snap and selection/grouping",
            MediaItemLowerLeftDragBehavior::AdjustTakePitchSemitones => "Adjust take pitch (semitones)",
            MediaItemLowerLeftDragBehavior::AdjustTakePitchFine => "Adjust take pitch (fine)",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelection => "Move item ignoring time selection",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelection => "Move item ignoring snap and time selection",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionAndSelectionGrouping => "Move item ignoring time selection and selection/grouping",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapTimeSelectionAndSelectionGrouping => "Move item ignoring snap, time selection, and selection/grouping",
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringTimeSelection => "Copy item ignoring time selection",
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelection => "Copy item ignoring snap and time selection",
            MediaItemLowerLeftDragBehavior::SelectTime => "Select time",
            MediaItemLowerLeftDragBehavior::AdjustItemVolume => "Adjust item volume",
            MediaItemLowerLeftDragBehavior::AdjustItemVolumeFine => "Adjust item volume (fine)",
            MediaItemLowerLeftDragBehavior::MoveItemAndTimeSelection => "Move item and time selection",
            MediaItemLowerLeftDragBehavior::MoveItemAndTimeSelectionIgnoringSnap => "Move item and time selection ignoring snap",
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelection => "Copy item and move time selection",
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnap => "Copy item and move time selection ignoring snap",
            MediaItemLowerLeftDragBehavior::SelectTimeIgnoringSnap => "Select time ignoring snap",
            MediaItemLowerLeftDragBehavior::MarqueeSelectItems => "Marquee select items",
            MediaItemLowerLeftDragBehavior::MarqueeSelectItemsAndTime => "Marquee select items and time",
            MediaItemLowerLeftDragBehavior::MarqueeSelectItemsAndTimeIgnoringSnap => "Marquee select items and time ignoring snap",
            MediaItemLowerLeftDragBehavior::MarqueeToggleItemSelection => "Marquee toggle item selection",
            MediaItemLowerLeftDragBehavior::MarqueeAddToItemSelection => "Marquee add to item selection",
            MediaItemLowerLeftDragBehavior::MoveItemVertically => "Move item vertically",
            MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringSelectionGrouping => "Move item vertically ignoring selection/grouping",
            MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelection => "Move item vertically ignoring time selection",
            MediaItemLowerLeftDragBehavior::MoveItemVerticallyIgnoringTimeSelectionAndSelectionGrouping => "Move item vertically ignoring time selection and selection/grouping",
            MediaItemLowerLeftDragBehavior::CopyItemVertically => "Copy item vertically",
            MediaItemLowerLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelection => "Copy item vertically ignoring time selection",
            MediaItemLowerLeftDragBehavior::MoveItemContentsIgnoringSelectionGrouping => "Move item contents ignoring selection/grouping",
            MediaItemLowerLeftDragBehavior::CopyItemPoolingMidiSourceData => "Copy item, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapPoolingMidiSourceData => "Copy item ignoring snap, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringTimeSelectionPoolingMidiSourceData => "Copy item ignoring time selection, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemIgnoringSnapAndTimeSelectionPoolingMidiSourceData => "Copy item ignoring snap and time selection, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemVerticallyPoolingMidiSourceData => "Copy item vertically, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemVerticallyIgnoringTimeSelectionPoolingMidiSourceData => "Copy item vertically ignoring time selection, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionPoolingMidiSourceData => "Copy item and move time selection, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::CopyItemAndMoveTimeSelectionIgnoringSnapPoolingMidiSourceData => "Copy item and move time selection ignoring snap, pooling MIDI source data",
            MediaItemLowerLeftDragBehavior::AdjustTakePan => "Adjust take pan",
            MediaItemLowerLeftDragBehavior::MarqueeZoom => "Marquee zoom",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionDisablingRippleEdit => "Move item ignoring time selection, disabling ripple edit",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForThisTrack => "Move item ignoring time selection, enabling ripple edit for this track",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringTimeSelectionEnablingRippleEditForAllTracks => "Move item ignoring time selection, enabling ripple edit for all tracks",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionDisablingRippleEdit => "Move item ignoring snap and time selection, disabling ripple edit",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForThisTrack => "Move item ignoring snap and time selection, enabling ripple edit for this track",
            MediaItemLowerLeftDragBehavior::MoveItemIgnoringSnapAndTimeSelectionEnablingRippleEditForAllTracks => "Move item ignoring snap and time selection, enabling ripple edit for all tracks",
            MediaItemLowerLeftDragBehavior::MoveItemContentsRippleAllAdjacentItems => "Move item contents, ripple all adjacent items",
            MediaItemLowerLeftDragBehavior::MoveItemContentsRippleEarlierAdjacentItems => "Move item contents, ripple earlier adjacent items",
            MediaItemLowerLeftDragBehavior::MoveItemContentsAndRightEdgeRippleLaterAdjacentItems => "Move item contents and right edge, ripple later adjacent items",
            MediaItemLowerLeftDragBehavior::SelectRazorEditArea => "Select razor edit area",
            MediaItemLowerLeftDragBehavior::SelectRazorEditAreaIgnoringSnap => "Select razor edit area ignoring snap",
            MediaItemLowerLeftDragBehavior::AddToRazorEditArea => "Add to razor edit area",
            MediaItemLowerLeftDragBehavior::AddToRazorEditAreaIgnoringSnap => "Add to razor edit area ignoring snap",
            MediaItemLowerLeftDragBehavior::SelectRazorEditAreaAndTime => "Select razor edit area and time",
            MediaItemLowerLeftDragBehavior::SelectRazorEditAreaAndTimeIgnoringSnap => "Select razor edit area and time ignoring snap",
            MediaItemLowerLeftDragBehavior::Unknown(_) => "Unknown behavior",
        }
    }
}

/// Media Item lower click behaviors
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaItemLowerClickBehavior {
    PassThroughToItemClickContext,
    SelectItemAndMoveEditCursor,
    SelectItemAndMoveEditCursorIgnoringSnap,
    SelectItem,
    ToggleItemSelection,
    AddARangeOfItemsToSelection,
    AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection,
    AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap,
    ExtendTimeSelection,
    ExtendTimeSelectionIgnoringSnap,
    AddARangeOfItemsToSelectionAndExtendTimeSelection,
    AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap,
    SelectItemIgnoringGrouping,
    RestorePreviousZoomScroll,
    RestorePreviousZoomLevel,
    AddStretchMarker,
    SelectRazorEditArea,
    ExtendRazorEditArea,
    Unknown(u32),
}

impl BehaviorId for MediaItemLowerClickBehavior {
    fn from_behavior_id(behavior_id: u32) -> Self {
        match behavior_id {
            0 => MediaItemLowerClickBehavior::PassThroughToItemClickContext,
            1 => MediaItemLowerClickBehavior::SelectItemAndMoveEditCursor,
            2 => MediaItemLowerClickBehavior::SelectItemAndMoveEditCursorIgnoringSnap,
            3 => MediaItemLowerClickBehavior::SelectItem,
            4 => MediaItemLowerClickBehavior::ToggleItemSelection,
            5 => MediaItemLowerClickBehavior::AddARangeOfItemsToSelection,
            6 => MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection,
            7 => MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap,
            8 => MediaItemLowerClickBehavior::ExtendTimeSelection,
            9 => MediaItemLowerClickBehavior::ExtendTimeSelectionIgnoringSnap,
            10 => MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelection,
            11 => MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap,
            12 => MediaItemLowerClickBehavior::SelectItemIgnoringGrouping,
            13 => MediaItemLowerClickBehavior::RestorePreviousZoomScroll,
            14 => MediaItemLowerClickBehavior::RestorePreviousZoomLevel,
            15 => MediaItemLowerClickBehavior::AddStretchMarker,
            19 => MediaItemLowerClickBehavior::SelectRazorEditArea,
            20 => MediaItemLowerClickBehavior::ExtendRazorEditArea,
            id => MediaItemLowerClickBehavior::Unknown(id),
        }
    }

    fn to_behavior_id(&self) -> u32 {
        match self {
            MediaItemLowerClickBehavior::PassThroughToItemClickContext => 0,
            MediaItemLowerClickBehavior::SelectItemAndMoveEditCursor => 1,
            MediaItemLowerClickBehavior::SelectItemAndMoveEditCursorIgnoringSnap => 2,
            MediaItemLowerClickBehavior::SelectItem => 3,
            MediaItemLowerClickBehavior::ToggleItemSelection => 4,
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelection => 5,
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection => 6,
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap => 7,
            MediaItemLowerClickBehavior::ExtendTimeSelection => 8,
            MediaItemLowerClickBehavior::ExtendTimeSelectionIgnoringSnap => 9,
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelection => 10,
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap => 11,
            MediaItemLowerClickBehavior::SelectItemIgnoringGrouping => 12,
            MediaItemLowerClickBehavior::RestorePreviousZoomScroll => 13,
            MediaItemLowerClickBehavior::RestorePreviousZoomLevel => 14,
            MediaItemLowerClickBehavior::AddStretchMarker => 15,
            MediaItemLowerClickBehavior::SelectRazorEditArea => 19,
            MediaItemLowerClickBehavior::ExtendRazorEditArea => 20,
            MediaItemLowerClickBehavior::Unknown(id) => *id,
        }
    }
}

impl BehaviorDisplay for MediaItemLowerClickBehavior {
    fn display_name(&self) -> &'static str {
        match self {
            MediaItemLowerClickBehavior::PassThroughToItemClickContext => "Pass through to item click context",
            MediaItemLowerClickBehavior::SelectItemAndMoveEditCursor => "Select item and move edit cursor",
            MediaItemLowerClickBehavior::SelectItemAndMoveEditCursorIgnoringSnap => "Select item and move edit cursor ignoring snap",
            MediaItemLowerClickBehavior::SelectItem => "Select item",
            MediaItemLowerClickBehavior::ToggleItemSelection => "Toggle item selection",
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelection => "Add a range of items to selection",
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelection => "Add a range of items to selection, if already selected extend time selection",
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionIfAlreadySelectedExtendTimeSelectionIgnoringSnap => "Add a range of items to selection, if already selected extend time selection ignoring snap",
            MediaItemLowerClickBehavior::ExtendTimeSelection => "Extend time selection",
            MediaItemLowerClickBehavior::ExtendTimeSelectionIgnoringSnap => "Extend time selection ignoring snap",
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelection => "Add a range of items to selection and extend time selection",
            MediaItemLowerClickBehavior::AddARangeOfItemsToSelectionAndExtendTimeSelectionIgnoringSnap => "Add a range of items to selection and extend time selection ignoring snap",
            MediaItemLowerClickBehavior::SelectItemIgnoringGrouping => "Select item ignoring grouping",
            MediaItemLowerClickBehavior::RestorePreviousZoomScroll => "Restore previous zoom/scroll",
            MediaItemLowerClickBehavior::RestorePreviousZoomLevel => "Restore previous zoom level",
            MediaItemLowerClickBehavior::AddStretchMarker => "Add stretch marker",
            MediaItemLowerClickBehavior::SelectRazorEditArea => "Select razor edit area",
            MediaItemLowerClickBehavior::ExtendRazorEditArea => "Extend razor edit area",
            MediaItemLowerClickBehavior::Unknown(_) => "Unknown behavior",
        }
    }
}

/// Media Item lower double click behaviors
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MediaItemLowerDoubleClickBehavior {
    PassThroughToItemDoubleClickContext,
    OpenMediaItemInExternalEditor,
    SetTimeSelectionToItem,
    SetLoopPointsToItem,
    ShowMediaItemProperties,
    ShowMediaItemSourceProperties,
    MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties,
    ShowTakeList,
    ShowTakePropsList,
    Unknown(u32),
}

impl BehaviorId for MediaItemLowerDoubleClickBehavior {
    fn from_behavior_id(behavior_id: u32) -> Self {
        match behavior_id {
            0 => MediaItemLowerDoubleClickBehavior::PassThroughToItemDoubleClickContext,
            1 => MediaItemLowerDoubleClickBehavior::OpenMediaItemInExternalEditor,
            2 => MediaItemLowerDoubleClickBehavior::SetTimeSelectionToItem,
            3 => MediaItemLowerDoubleClickBehavior::SetLoopPointsToItem,
            4 => MediaItemLowerDoubleClickBehavior::ShowMediaItemProperties,
            5 => MediaItemLowerDoubleClickBehavior::ShowMediaItemSourceProperties,
            6 => MediaItemLowerDoubleClickBehavior::MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties,
            7 => MediaItemLowerDoubleClickBehavior::ShowTakeList,
            8 => MediaItemLowerDoubleClickBehavior::ShowTakePropsList,
            id => MediaItemLowerDoubleClickBehavior::Unknown(id),
        }
    }

    fn to_behavior_id(&self) -> u32 {
        match self {
            MediaItemLowerDoubleClickBehavior::PassThroughToItemDoubleClickContext => 0,
            MediaItemLowerDoubleClickBehavior::OpenMediaItemInExternalEditor => 1,
            MediaItemLowerDoubleClickBehavior::SetTimeSelectionToItem => 2,
            MediaItemLowerDoubleClickBehavior::SetLoopPointsToItem => 3,
            MediaItemLowerDoubleClickBehavior::ShowMediaItemProperties => 4,
            MediaItemLowerDoubleClickBehavior::ShowMediaItemSourceProperties => 5,
            MediaItemLowerDoubleClickBehavior::MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties => 6,
            MediaItemLowerDoubleClickBehavior::ShowTakeList => 7,
            MediaItemLowerDoubleClickBehavior::ShowTakePropsList => 8,
            MediaItemLowerDoubleClickBehavior::Unknown(id) => *id,
        }
    }
}

impl BehaviorDisplay for MediaItemLowerDoubleClickBehavior {
    fn display_name(&self) -> &'static str {
        match self {
            MediaItemLowerDoubleClickBehavior::PassThroughToItemDoubleClickContext => "Pass through to item double-click context",
            MediaItemLowerDoubleClickBehavior::OpenMediaItemInExternalEditor => "Open media item in external editor",
            MediaItemLowerDoubleClickBehavior::SetTimeSelectionToItem => "Set time selection to item",
            MediaItemLowerDoubleClickBehavior::SetLoopPointsToItem => "Set loop points to item",
            MediaItemLowerDoubleClickBehavior::ShowMediaItemProperties => "Show media item properties",
            MediaItemLowerDoubleClickBehavior::ShowMediaItemSourceProperties => "Show media item source properties",
            MediaItemLowerDoubleClickBehavior::MidiOpenInEditorSubprojectsOpenProjectAudioShowMediaItemProperties => "MIDI: open in editor, Subprojects: open project, Audio: show media item properties",
            MediaItemLowerDoubleClickBehavior::ShowTakeList => "Show take list",
            MediaItemLowerDoubleClickBehavior::ShowTakePropsList => "Show take props list",
            MediaItemLowerDoubleClickBehavior::Unknown(_) => "Unknown behavior",
        }
    }
}
