//! XDG desktop entry and wrapper script generation for Linux.
//!
//! Provides functions to generate and install:
//! - `.desktop` files for application menus
//! - Wrapper shell scripts that set `FTS_LAUNCH_CONFIG` and exec `reaper-launcher`
//! - `launch.json` config files in XDG-compliant locations
//!
//! Used by xtask `setup-rigs` to create named REAPER instances that appear
//! as separate applications in Linux desktop environments.

use crate::config::LaunchConfig;
use std::path::{Path, PathBuf};

/// Configuration for generating a `.desktop` file.
pub struct DesktopEntryConfig {
    /// Unique identifier, e.g., "daw-test", "fts-guitar".
    pub id: String,
    /// Human-readable name, e.g., "DAW Test", "FTS Guitar".
    pub name: String,
    /// One-line description for the Comment= field.
    pub comment: String,
    /// Icon name without extension, e.g., "fts-daw-test".
    pub icon_name: String,
    /// Full Exec= line value, e.g., "$HOME/.local/bin/fts-daw-test %F".
    pub exec_command: String,
    /// XDG categories, e.g., "AudioVideo;Audio;".
    pub categories: String,
    /// Search keywords for desktop search.
    pub keywords: Vec<String>,
}

/// Generate the contents of a `.desktop` file.
pub fn generate_desktop_entry(config: &DesktopEntryConfig) -> String {
    let keywords = if config.keywords.is_empty() {
        String::new()
    } else {
        let mut kw = config.keywords.join(";");
        kw.push(';');
        format!("Keywords={kw}\n")
    };

    format!(
        "[Desktop Entry]\n\
         Type=Application\n\
         Name={name}\n\
         Comment={comment}\n\
         Exec={exec}\n\
         Icon={icon}\n\
         Terminal=false\n\
         Categories={categories}\n\
         StartupWMClass=REAPER\n\
         {keywords}",
        name = config.name,
        comment = config.comment,
        exec = config.exec_command,
        icon = config.icon_name,
        categories = config.categories,
        keywords = keywords,
    )
}

/// Write a `.desktop` file to `~/.local/share/applications/{id}.desktop`.
///
/// Creates parent directories if needed. Returns the path written.
pub fn install_desktop_entry(config: &DesktopEntryConfig) -> Result<PathBuf, String> {
    let home = home_dir()?;
    let dir = home.join(".local/share/applications");
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create {}: {e}", dir.display()))?;

    let path = dir.join(format!("{}.desktop", config.id));
    let content = generate_desktop_entry(config);
    std::fs::write(&path, &content)
        .map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    // Mark as executable (freedesktop spec recommends it)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755));
    }

    Ok(path)
}

/// Write a `launch.json` to `~/.config/fts/rigs/{id}/launch.json`.
///
/// Creates parent directories if needed. Returns the path written.
pub fn install_launch_config(id: &str, config: &LaunchConfig) -> Result<PathBuf, String> {
    let home = home_dir()?;
    let dir = home.join(format!(".config/fts/rigs/{id}"));
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create {}: {e}", dir.display()))?;

    let path = dir.join("launch.json");
    config.save(&path)?;
    Ok(path)
}

/// Generate a wrapper shell script that launches reaper-launcher with the
/// given `launch.json` path.
///
/// `launcher_bin` is the path to the `reaper-launcher` binary (e.g.,
/// `$HOME/.local/bin/reaper-launcher`). Using a full path ensures the script
/// works regardless of whether `~/.local/bin` is on PATH.
///
/// If `fhs_wrapper` is provided (e.g., `"reaper-env"`), it's prepended to
/// the exec chain to set up the FHS environment (Nix).
pub fn generate_wrapper_script(
    launch_json_path: &Path,
    launcher_bin: &Path,
    fhs_wrapper: Option<&str>,
) -> String {
    let config_path = launch_json_path.display();
    let launcher = launcher_bin.display();
    let exec_prefix = match fhs_wrapper {
        Some(wrapper) => format!("{wrapper} "),
        None => String::new(),
    };

    format!(
        "#!/usr/bin/env bash\n\
         # Generated by: cargo xtask setup-rigs\n\
         exec {exec_prefix}\"{launcher}\" --config \"{config_path}\" \"$@\"\n"
    )
}

/// Write a wrapper script to `~/.local/bin/{id}`.
///
/// Creates the directory and marks the script as executable.
/// Returns the path written.
pub fn install_wrapper_script(id: &str, content: &str) -> Result<PathBuf, String> {
    let home = home_dir()?;
    let dir = home.join(".local/bin");
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create {}: {e}", dir.display()))?;

    let path = dir.join(id);
    std::fs::write(&path, content)
        .map_err(|e| format!("Failed to write {}: {e}", path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("Failed to chmod {}: {e}", path.display()))?;
    }

    Ok(path)
}

/// Run `update-desktop-database` if available, to refresh the desktop menu cache.
pub fn refresh_desktop_database() {
    let home = match home_dir() {
        Ok(h) => h,
        Err(_) => return,
    };
    let apps_dir = home.join(".local/share/applications");
    let _ = std::process::Command::new("update-desktop-database")
        .arg(&apps_dir)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();
}

fn home_dir() -> Result<PathBuf, String> {
    std::env::var("HOME")
        .map(PathBuf::from)
        .map_err(|_| "HOME environment variable not set".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_desktop_entry() {
        let config = DesktopEntryConfig {
            id: "fts-daw-test".to_string(),
            name: "DAW Test".to_string(),
            comment: "REAPER integration test instance".to_string(),
            icon_name: "fts-daw-test".to_string(),
            exec_command: "$HOME/.local/bin/fts-daw-test %F".to_string(),
            categories: "AudioVideo;Audio;".to_string(),
            keywords: vec!["reaper".to_string(), "daw".to_string(), "test".to_string()],
        };
        let entry = generate_desktop_entry(&config);
        assert!(entry.contains("[Desktop Entry]"));
        assert!(entry.contains("Name=DAW Test"));
        assert!(entry.contains("Icon=fts-daw-test"));
        assert!(entry.contains("Keywords=reaper;daw;test;"));
        assert!(entry.contains("StartupWMClass=REAPER"));
    }

    #[test]
    fn test_generate_wrapper_script_with_fhs() {
        let path = PathBuf::from("/home/user/.config/fts/rigs/daw-test/launch.json");
        let launcher = PathBuf::from("/home/user/.local/bin/reaper-launcher");
        let script = generate_wrapper_script(&path, &launcher, Some("reaper-env"));
        assert!(script.starts_with("#!/usr/bin/env bash"));
        assert!(script.contains("exec reaper-env"));
        assert!(script.contains("reaper-launcher"));
        assert!(script.contains("launch.json"));
    }

    #[test]
    fn test_generate_wrapper_script_without_fhs() {
        let path = PathBuf::from("/home/user/.config/fts/rigs/daw-test/launch.json");
        let launcher = PathBuf::from("/home/user/.local/bin/reaper-launcher");
        let script = generate_wrapper_script(&path, &launcher, None);
        assert!(script.contains("reaper-launcher"));
        assert!(script.contains("--config"));
        assert!(!script.contains("reaper-env"));
    }
}
