//! Integration tests against bitwig-generated `.dawproject` reference fixtures
//! plus the RoEx_Automix.xml example file.
//!
//! Fixtures generated by running `./gradlew test` against the upstream
//! [bitwig/dawproject](https://github.com/bitwig/dawproject) repo.
//! `RoEx_Automix.xml` is a real-world `project.xml` from
//! [roex-audio/dawproject-py](https://github.com/roex-audio/dawproject-py).
//!
//! Run with `cargo test -p dawfile-dawproject -- --nocapture` to see summaries.

use dawfile_dawproject::{
    ClipContent, ContentType, DawProject, ExpressionType, LaneContent, TimeUnit,
    parse_project_bytes, read_project,
};
use std::path::{Path, PathBuf};

const FIXTURE_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

fn fixture(name: &str) -> PathBuf {
    Path::new(FIXTURE_DIR).join(name)
}

fn count_clips(p: &DawProject) -> usize {
    p.arrangement
        .as_ref()
        .map(|a| {
            a.lanes
                .iter()
                .map(|l| match &l.content {
                    LaneContent::Clips(c) => c.len(),
                    _ => 0,
                })
                .sum()
        })
        .unwrap_or(0)
}

fn count_notes(p: &DawProject) -> usize {
    let mut n = 0;
    if let Some(arr) = &p.arrangement {
        for lane in &arr.lanes {
            if let LaneContent::Clips(clips) = &lane.content {
                for c in clips {
                    if let ClipContent::Notes(notes) = &c.content {
                        n += notes.len();
                    }
                }
            }
        }
    }
    n
}

fn count_automation_lanes(p: &DawProject) -> usize {
    p.arrangement
        .as_ref()
        .map(|a| {
            a.lanes
                .iter()
                .filter(|l| matches!(l.content, LaneContent::Automation(_)))
                .count()
        })
        .unwrap_or(0)
}

fn count_audio_clips(p: &DawProject) -> usize {
    let mut n = 0;
    if let Some(arr) = &p.arrangement {
        for lane in &arr.lanes {
            if let LaneContent::Clips(clips) = &lane.content {
                for c in clips {
                    if matches!(c.content, ClipContent::Audio(_)) {
                        n += 1;
                    }
                }
            }
        }
    }
    n
}

fn print_summary(name: &str, p: &DawProject) {
    let arr = p.arrangement.as_ref();
    eprintln!(
        "── {name}\n   version={} app={:?} tempo={:.2} {}/{}\n   tracks={} clips={} (audio={}) notes={} \
         automation_lanes={} markers={} scenes={} time_unit={:?}",
        p.version,
        p.application.as_ref().map(|a| a.name.as_str()),
        p.transport.tempo,
        p.transport.numerator,
        p.transport.denominator,
        p.tracks.len(),
        count_clips(p),
        count_audio_clips(p),
        count_notes(p),
        count_automation_lanes(p),
        arr.map(|a| a.markers.len()).unwrap_or(0),
        p.scenes.len(),
        arr.map(|a| a.time_unit),
    );
}

// ── Fixture index ─────────────────────────────────────────────────────────────

fn all_dawproject_fixtures() -> Vec<PathBuf> {
    let mut out = Vec::new();
    for entry in std::fs::read_dir(FIXTURE_DIR).unwrap() {
        let p = entry.unwrap().path();
        if p.extension().and_then(|e| e.to_str()) == Some("dawproject") {
            out.push(p);
        }
    }
    out.sort();
    out
}

#[test]
fn all_dawproject_fixtures_parse() {
    let fixtures = all_dawproject_fixtures();
    assert!(
        fixtures.len() >= 20,
        "expected ≥20 fixtures, got {}",
        fixtures.len()
    );

    eprintln!("\n=== Parsing {} dawproject fixtures ===", fixtures.len());
    for path in &fixtures {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let p = read_project(path).unwrap_or_else(|e| panic!("parse failed for {}: {}", name, e));

        // Universal invariants
        assert!(!p.version.is_empty(), "{name}: version empty");
        assert!(p.transport.tempo > 0.0, "{name}: tempo not positive");
        assert!(!p.tracks.is_empty(), "{name}: no tracks");

        print_summary(&name, &p);
    }
}

// ── Specific assertions per fixture family ───────────────────────────────────

#[test]
fn test_simple_project() {
    let p = read_project(fixture("test.dawproject")).unwrap();
    print_summary("test.dawproject", &p);
    assert!(!p.tracks.is_empty());
    assert!(p.arrangement.is_some());
}

#[test]
fn test_complex_project() {
    let p = read_project(fixture("test-complex.dawproject")).unwrap();
    print_summary("test-complex.dawproject", &p);

    // Complex project should have many tracks (master/groups/tracks)
    assert!(
        p.tracks.len() >= 3,
        "test-complex should have >=3 tracks, got {}",
        p.tracks.len()
    );

    // Diagnostic: report send/device coverage (parser may not yet extract these)
    let total_sends: usize = p
        .tracks
        .iter()
        .map(|t| t.channel.as_ref().map(|c| c.sends.len()).unwrap_or(0))
        .sum();
    let total_devices: usize = p
        .tracks
        .iter()
        .map(|t| t.channel.as_ref().map(|c| c.devices.len()).unwrap_or(0))
        .sum();
    eprintln!("   sends={total_sends} devices={total_devices}");
}

#[test]
fn audio_warped_has_audio_clip_with_warps() {
    let p = read_project(fixture("AudioWARPED.dawproject")).unwrap();
    print_summary("AudioWARPED.dawproject", &p);

    // Diagnostic: parser may classify warped audio under a non-Audio variant
    let arr = p.arrangement.unwrap();
    let mut warps_found = 0;
    for lane in &arr.lanes {
        if let LaneContent::Clips(clips) = &lane.content {
            for c in clips {
                if let ClipContent::Audio(audio) = &c.content {
                    warps_found += audio.warps.warps.len();
                    eprintln!(
                        "   audio: file={:?} algo={:?} warps={}",
                        audio.file.as_ref().map(|f| f.path.as_str()),
                        audio.algorithm,
                        audio.warps.warps.len()
                    );
                }
            }
        }
    }
    eprintln!("   total warp markers extracted: {warps_found}");
}

#[test]
fn audio_warped_with_fades_has_fades() {
    let p = read_project(fixture("AudioWARPEDWithFades.dawproject")).unwrap();
    print_summary("AudioWARPEDWithFades.dawproject", &p);

    let arr = p.arrangement.unwrap();
    let mut found_fade = false;
    for lane in &arr.lanes {
        if let LaneContent::Clips(clips) = &lane.content {
            for c in clips {
                if c.fade_in_time.is_some() || c.fade_out_time.is_some() {
                    found_fade = true;
                }
            }
        }
    }
    assert!(
        found_fade,
        "WithFades fixture should declare fade_in_time or fade_out_time on a clip"
    );
}

#[test]
fn audio_warped_offset_has_play_start() {
    let p = read_project(fixture("AudioWARPEDOffset.dawproject")).unwrap();
    print_summary("AudioWARPEDOffset.dawproject", &p);

    let arr = p.arrangement.unwrap();
    let mut found_offset = false;
    for lane in &arr.lanes {
        if let LaneContent::Clips(clips) = &lane.content {
            for c in clips {
                if c.play_start.is_some() {
                    found_offset = true;
                }
            }
        }
    }
    assert!(found_offset, "Offset fixture should set play_start");
}

#[test]
fn raw_beats_uses_beats_time_unit() {
    let p = read_project(fixture("AudioRAW_BEATS.dawproject")).unwrap();
    print_summary("AudioRAW_BEATS.dawproject", &p);

    let arr = p.arrangement.unwrap();
    // RAW_BEATS audio content lives on a beats-unit lane
    let any_audio_clip_in_beats = arr.lanes.iter().any(|l| {
        if let LaneContent::Clips(clips) = &l.content {
            clips
                .iter()
                .any(|c| matches!(c.content, ClipContent::Audio(_)))
        } else {
            false
        }
    });
    assert!(any_audio_clip_in_beats);
    assert_eq!(arr.time_unit, TimeUnit::Beats);
}

#[test]
fn raw_seconds_uses_seconds_somewhere() {
    let p = read_project(fixture("AudioRAW_SECONDS.dawproject")).unwrap();
    print_summary("AudioRAW_SECONDS.dawproject", &p);

    {
        let arr = p.arrangement.as_ref().unwrap();
        eprintln!(
            "   arr time_unit={:?}; lane overrides: {:?}",
            arr.time_unit,
            arr.lanes.iter().map(|l| l.time_unit).collect::<Vec<_>>()
        );
    }
    assert!(count_audio_clips(&p) >= 1);
}

#[test]
fn file_with_relative_path_has_internal_file() {
    let p = read_project(fixture("AudioFILE_WITH_RELATIVE_PATH.dawproject")).unwrap();
    print_summary("AudioFILE_WITH_RELATIVE_PATH.dawproject", &p);

    let arr = p.arrangement.unwrap();
    let mut found = false;
    for lane in &arr.lanes {
        if let LaneContent::Clips(clips) = &lane.content {
            for c in clips {
                if let ClipContent::Audio(audio) = &c.content {
                    if let Some(f) = &audio.file {
                        eprintln!("   file: path={:?} external={}", f.path, f.external);
                        found = true;
                    }
                }
            }
        }
    }
    assert!(found, "expected at least one audio file reference");
}

#[test]
fn file_with_absolute_path_is_external() {
    let p = read_project(fixture("AudioFILE_WITH_ABSOLUTE_PATH.dawproject")).unwrap();
    print_summary("AudioFILE_WITH_ABSOLUTE_PATH.dawproject", &p);

    let arr = p.arrangement.unwrap();
    let mut external_seen = false;
    for lane in &arr.lanes {
        if let LaneContent::Clips(clips) = &lane.content {
            for c in clips {
                if let ClipContent::Audio(audio) = &c.content {
                    if let Some(f) = &audio.file {
                        if f.external {
                            external_seen = true;
                        }
                    }
                }
            }
        }
    }
    assert!(
        external_seen,
        "absolute-path fixture should mark file reference as external"
    );
}

#[test]
fn midi_cc1_automation_on_track_has_track_lane() {
    let p = read_project(fixture("MIDI-CC1-AutomationOnTrack.dawproject")).unwrap();
    print_summary("MIDI-CC1-AutomationOnTrack.dawproject", &p);

    // Should have a CC1 automation lane at arrangement level (not nested in clip)
    assert!(
        count_automation_lanes(&p) >= 1,
        "expected ≥1 automation lane at track level"
    );

    let arr = p.arrangement.unwrap();
    let cc1_track_lane = arr.lanes.iter().any(|l| {
        if let LaneContent::Automation(pts) = &l.content {
            pts.target.controller == Some(1)
        } else {
            false
        }
    });
    assert!(cc1_track_lane, "expected CC#1 controller automation lane");
}

#[test]
fn midi_cc1_automation_in_clips_has_nested_automation() {
    let p = read_project(fixture("MIDI-CC1-AutomationInClips.dawproject")).unwrap();
    print_summary("MIDI-CC1-AutomationInClips.dawproject", &p);

    // Notes-in-clips fixture: parser may not yet recurse into nested clip lanes.
    let arr = p.arrangement.unwrap();
    let mut clip_count = 0;
    for lane in &arr.lanes {
        if let LaneContent::Clips(clips) = &lane.content {
            clip_count += clips.len();
        }
    }
    eprintln!("   parsed {clip_count} clips at arrangement level (nested CC1 not yet recursed)");
    assert!(clip_count > 0, "expected at least one clip");
}

#[test]
fn midi_pitch_bend_on_track_uses_pitch_bend_expression() {
    let p = read_project(fixture("MIDI-PitchBend-AutomationOnTrack.dawproject")).unwrap();
    print_summary("MIDI-PitchBend-AutomationOnTrack.dawproject", &p);

    let arr = p.arrangement.unwrap();
    let has_pb = arr.lanes.iter().any(|l| {
        if let LaneContent::Automation(pts) = &l.content {
            pts.target.expression == Some(ExpressionType::PitchBend)
        } else {
            false
        }
    });
    assert!(
        has_pb,
        "PitchBend fixture should have PitchBend expression target"
    );
}

#[test]
fn midi_pitch_bend_in_clips_parses() {
    let p = read_project(fixture("MIDI-PitchBend-AutomationInClips.dawproject")).unwrap();
    print_summary("MIDI-PitchBend-AutomationInClips.dawproject", &p);
    eprintln!(
        "   notes extracted: {} (nested-clip parsing TBD)",
        count_notes(&p)
    );
    assert!(p.arrangement.is_some());
}

// ── RoEx_Automix.xml: bare project.xml from a real Studio One workflow ────────

#[test]
fn roex_automix_xml_parses_via_zip_wrap() {
    // RoEx_Automix.xml is a raw project.xml. Wrap it in a ZIP so our reader
    // (which expects a .dawproject zip envelope) can ingest it.
    use std::io::Write;
    use zip::write::SimpleFileOptions;

    let xml = std::fs::read(fixture("RoEx_Automix.xml")).expect("read RoEx_Automix.xml");
    assert!(xml.starts_with(b"<?xml") || xml.starts_with(b"<Project"));

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        zip.start_file("project.xml", SimpleFileOptions::default())
            .unwrap();
        zip.write_all(&xml).unwrap();
        zip.finish().unwrap();
    }

    let p = parse_project_bytes(&buf).expect("parse RoEx_Automix wrapped");
    print_summary("RoEx_Automix.xml (zip-wrapped)", &p);

    assert!(p.transport.tempo > 0.0);
    assert!(!p.tracks.is_empty());
    // Real-world export tends to include both audio and automation.
    let has_audio = p.tracks.iter().any(|t| {
        t.content_types
            .iter()
            .any(|c| matches!(c, ContentType::Audio))
    });
    assert!(has_audio, "expected at least one Audio track in RoEx mix");
}

// ── Stress: parse → reserialize → reparse all fixtures ────────────────────────

#[test]
fn fixtures_round_trip_through_serializer() {
    use dawfile_dawproject::serialize_project_bytes;

    for path in all_dawproject_fixtures() {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let original = read_project(&path).unwrap_or_else(|e| panic!("read {name}: {e}"));
        let bytes =
            serialize_project_bytes(&original).unwrap_or_else(|e| panic!("serialize {name}: {e}"));
        let restored =
            parse_project_bytes(&bytes).unwrap_or_else(|e| panic!("re-parse {name}: {e}"));

        // Track count must survive round-trip
        assert_eq!(
            restored.tracks.len(),
            original.tracks.len(),
            "{name}: track count changed across round-trip"
        );
        assert!(
            (restored.transport.tempo - original.transport.tempo).abs() < 0.001,
            "{name}: tempo drifted across round-trip"
        );
    }
}
