[package]
name = "nice-plug-egui"
version = "0.1.3"
authors = [
    "Billy Messenger <billydm@noreply.codeberg.org>",
    "Robbert van der Helm <mail@robbertvanderhelm.nl>",
]
description = "An adapter to use egui GUIs with nice-plug"
edition.workspace = true
license = "ISC"
repository = "https://codeberg.org/BillyDM/nice-plug"
keywords = ["gui", "nice-plug", "plugin", "clap", "vst3"]
categories = ["gui"]

[features]
default = ["opengl"]
opengl = ["egui-baseview/opengl"]
wgpu = ["egui-baseview/wgpu"]
## Enables a temporary workaround for keyboard input not working sometimes.
## See https://github.com/BillyDM/egui-baseview/issues/20
keyboard_focus_workaround = ["egui-baseview/keyboard_focus_workaround"]

[dependencies]
raw-window-handle.workspace = true
nice-plug-core.workspace = true
egui-baseview = { workspace = true, features = [
    "nice-log",
] }
egui.workspace = true
crossbeam.workspace = true
parking_lot.workspace = true
# To make the state persistable
serde.workspace = true
